id = "nexusflow"
name = "NexusFlow"
description = "The open source coding agent."
version = "1.15.12"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/nexusflow"

[agent_servers.nexusflow]
name = "NexusFlow"
icon = "./icons/nexusflow.svg"

[agent_servers.nexusflow.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/nexusflow/releases/download/v1.15.12/nexusflow-darwin-arm64.zip"
cmd = "./nexusflow"
args = ["acp"]

[agent_servers.nexusflow.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/nexusflow/releases/download/v1.15.12/nexusflow-darwin-x64.zip"
cmd = "./nexusflow"
args = ["acp"]

[agent_servers.nexusflow.targets.linux-aarch64]
archive = "https://github.com/anomalyco/nexusflow/releases/download/v1.15.12/nexusflow-linux-arm64.tar.gz"
cmd = "./nexusflow"
args = ["acp"]

[agent_servers.nexusflow.targets.linux-x86_64]
archive = "https://github.com/anomalyco/nexusflow/releases/download/v1.15.12/nexusflow-linux-x64.tar.gz"
cmd = "./nexusflow"
args = ["acp"]

[agent_servers.nexusflow.targets.windows-x86_64]
archive = "https://github.com/anomalyco/nexusflow/releases/download/v1.15.12/nexusflow-windows-x64.zip"
cmd = "./nexusflow.exe"
args = ["acp"]
