import { Config } from "effect"

function env(key: string) {
  return process.env[key.replace(/^NEXUSFLOW_/, "NEXUSFLOW_")] ?? process.env[key]
}

function truthy(key: string) {
  const value = env(key)?.toLowerCase()
  return value === "true" || value === "1"
}

const NEXUSFLOW_EXPERIMENTAL = truthy("NEXUSFLOW_EXPERIMENTAL")
const copy = env("NEXUSFLOW_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")

function enabledByExperimental(key: string) {
  return env(key) === undefined ? NEXUSFLOW_EXPERIMENTAL : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  NEXUSFLOW_AUTO_HEAP_SNAPSHOT: truthy("NEXUSFLOW_AUTO_HEAP_SNAPSHOT"),
  NEXUSFLOW_GIT_BASH_PATH: env("NEXUSFLOW_GIT_BASH_PATH"),
  NEXUSFLOW_CONFIG: env("NEXUSFLOW_CONFIG"),
  NEXUSFLOW_CONFIG_CONTENT: env("NEXUSFLOW_CONFIG_CONTENT"),
  NEXUSFLOW_DISABLE_AUTOUPDATE: truthy("NEXUSFLOW_DISABLE_AUTOUPDATE"),
  NEXUSFLOW_ALWAYS_NOTIFY_UPDATE: truthy("NEXUSFLOW_ALWAYS_NOTIFY_UPDATE"),
  NEXUSFLOW_DISABLE_PRUNE: truthy("NEXUSFLOW_DISABLE_PRUNE"),
  NEXUSFLOW_DISABLE_TERMINAL_TITLE: truthy("NEXUSFLOW_DISABLE_TERMINAL_TITLE"),
  NEXUSFLOW_SHOW_TTFD: truthy("NEXUSFLOW_SHOW_TTFD"),
  NEXUSFLOW_DISABLE_AUTOCOMPACT: truthy("NEXUSFLOW_DISABLE_AUTOCOMPACT"),
  NEXUSFLOW_DISABLE_MODELS_FETCH: truthy("NEXUSFLOW_DISABLE_MODELS_FETCH"),
  NEXUSFLOW_DISABLE_MOUSE: truthy("NEXUSFLOW_DISABLE_MOUSE"),
  NEXUSFLOW_FAKE_VCS: env("NEXUSFLOW_FAKE_VCS"),
  NEXUSFLOW_SERVER_PASSWORD: env("NEXUSFLOW_SERVER_PASSWORD"),
  NEXUSFLOW_SERVER_USERNAME: env("NEXUSFLOW_SERVER_USERNAME"),

  // Experimental
  NEXUSFLOW_EXPERIMENTAL_FILEWATCHER: Config.boolean("NEXUSFLOW_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  NEXUSFLOW_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("NEXUSFLOW_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  NEXUSFLOW_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("NEXUSFLOW_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  NEXUSFLOW_MODELS_URL: env("NEXUSFLOW_MODELS_URL"),
  NEXUSFLOW_MODELS_PATH: env("NEXUSFLOW_MODELS_PATH"),
  NEXUSFLOW_DB: env("NEXUSFLOW_DB"),

  NEXUSFLOW_WORKSPACE_ID: env("NEXUSFLOW_WORKSPACE_ID"),
  NEXUSFLOW_EXPERIMENTAL_WORKSPACES: enabledByExperimental("NEXUSFLOW_EXPERIMENTAL_WORKSPACES"),
  NEXUSFLOW_EXPERIMENTAL_SESSION_SWITCHER: enabledByExperimental("NEXUSFLOW_EXPERIMENTAL_SESSION_SWITCHER"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get NEXUSFLOW_DISABLE_PROJECT_CONFIG() {
    return truthy("NEXUSFLOW_DISABLE_PROJECT_CONFIG")
  },
  get NEXUSFLOW_TUI_CONFIG() {
    return env("NEXUSFLOW_TUI_CONFIG")
  },
  get NEXUSFLOW_CONFIG_DIR() {
    return env("NEXUSFLOW_CONFIG_DIR")
  },
  get NEXUSFLOW_PURE() {
    return truthy("NEXUSFLOW_PURE")
  },
  get NEXUSFLOW_PERMISSION() {
    return env("NEXUSFLOW_PERMISSION")
  },
  get NEXUSFLOW_PLUGIN_META_FILE() {
    return env("NEXUSFLOW_PLUGIN_META_FILE")
  },
  get NEXUSFLOW_CLIENT() {
    return env("NEXUSFLOW_CLIENT") ?? "cli"
  },
}
